{
  "metadata": {
    "copyright": ["2025 Evgeni Chasnovski <evgeni.chasnovski@gmail.com>"],
    "license": "MIT",
    "name": "Minischeme Dark"
  },
  "background-color": "#081823",
  "text-styles": {
    "Normal": {
      "text-color": "#D4D4D4",
      "selected-text-color": "#D4D4D4",
      "bold": false,
      "italic": false,
      "underline": false,
      "strike-through": false
    },
    "Keyword": {
      "text-color": "#D4D4D4",
      "selected-text-color": "#D4D4D4",
      "bold": true
    },
    "Function": {
      "text-color": "#A1DDFF",
      "selected-text-color": "#A1DDFF"
    },
    "Variable": {
      "text-color": "#D4D4D4",
      "selected-text-color": "#D4D4D4"
    },
    "ControlFlow": {
      "text-color": "#D4D4D4",
      "selected-text-color": "#D4D4D4",
      "bold": true
    },
    "Operator": {
      "text-color": "#E0D699",
      "selected-text-color": "#E0D699"
    },
    "BuiltIn": {
      "text-color": "#94E6E5",
      "selected-text-color": "#94E6E5"
    },
    "Extension": {
      "text-color": "#94E6E5",
      "selected-text-color": "#94E6E5",
      "bold": true
    },
    "Preprocessor": {
      "text-color": "#A1DDFF",
      "selected-text-color": "#A1DDFF"
    },
    "Attribute": {
      "text-color": "#A1DDFF",
      "selected-text-color": "#A1DDFF"
    },
    "Char": {
      "text-color": "#B4E3B5",
      "selected-text-color": "#B4E3B5"
    },
    "SpecialChar": {
      "text-color": "#E0D699",
      "selected-text-color": "#E0D699"
    },
    "String": {
      "text-color": "#B4E3B5",
      "selected-text-color": "#B4E3B5"
    },
    "VerbatimString": {
      "text-color": "#B4E3B5",
      "selected-text-color": "#B4E3B5"
    },
    "SpecialString": {
      "text-color": "#B4E3B5",
      "selected-text-color": "#B4E3B5"
    },
    "Import": {
      "text-color": "#B4E3B5",
      "selected-text-color": "#B4E3B5"
    },
    "DataType": {
      "text-color": "#F0C3F2",
      "selected-text-color": "#F0C3F2"
    },
    "DecVal": {
      "text-color": "#F0C3F2",
      "selected-text-color": "#F0C3F2"
    },
    "BaseN": {
      "text-color": "#F0C3F2",
      "selected-text-color": "#F0C3F2"
    },
    "Float": {
      "text-color": "#F0C3F2",
      "selected-text-color": "#F0C3F2"
    },
    "Constant": {
      "text-color": "#94E6E5",
      "selected-text-color": "#94E6E5",
      "bold": true
    },
    "Comment": {
      "text-color": "#919191",
      "selected-text-color": "#919191"
    },
    "Documentation": {
      "text-color": "#919191",
      "selected-text-color": "#919191"
    },
    "Annotation": {
      "text-color": "#FFC0C4",
      "selected-text-color": "#FFC0C4"
    },
    "CommentVar": {
      "text-color": "#94E6E5",
      "selected-text-color": "#94E6E5"
    },
    "RegionMarker": {
      "text-color": "#919191",
      "selected-text-color": "#919191"
    },
    "Information": {
      "text-color": "#A1DDFF",
      "selected-text-color": "#A1DDFF"
    },
    "Warning": {
      "text-color": "#E0D699",
      "selected-text-color": "#E0D699"
    },
    "Alert": {
      "text-color": "#E0D699",
      "selected-text-color": "#E0D699",
      "bold": true
    },
    "Error": {
      "text-color": "#FFC0C4",
      "selected-text-color": "#FFC0C4",
      "underline": true
    },
    "Others": {
      "text-color": "#D4D4D4",
      "selected-text-color": "#D4D4D4"
    }
  },
  "custom-styles": {
    "Diff": {
      "Removed line": {
        "text-color": "#FFC0C4",
        "selected-text-color": "#FFC0C4"
      },
      "Added line": {
        "text-color": "#AFE4B9",
        "selected-text-color": "#AFE4B9"
      }
    }
  }
}
